version: '3.1'
services:
  qummy:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/app
    env_file:
      - ./.env
    ports:
      - 8000:8000
    command: bash -c "
      ls &&
      alembic upgrade head &&
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "